-d D:\Nano4KProjects\nano4k_spi_nor_flash\impl\gwsynthesis\nano4k_spi_nor_flash.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\Nano4KProjects\nano4k_spi_nor_flash\src\nano4k_spi_nor_flash.cst
-cfg D:\Nano4KProjects\nano4k_spi_nor_flash\impl\pnr\device.cfg
-sdc D:\Nano4KProjects\nano4k_spi_nor_flash\src\nano4k_spi_nor_flash.sdc
-gao_crc 1000011010101101
-bit
-tr
-ph
-timing
-cst_error
-rtl_gao
